import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

// import data from "../data.json";

export default function Home({ data }) {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex w-screen items-center justify-between bg-red-300">
        <h3
          className={`font-weight-bold w-1/6 bg-gradient-to-br from-cyan-400 to-blue-500 px-4 py-2 text-center text-3xl text-white ${styles.logo}`}
        >
          logo
        </h3>
        <ul className="children:mx-6 flex  w-5/6 justify-center">
          <li className="">
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
            <Link href="/work">Work</Link>
          </li>
          <li>
            <Link href="/contact">Contact</Link>
          </li>
        </ul>
      </nav>

      <main className="container text-black">
        <ul>
          {data.map((item) => (
            <li key={item.id}>{item.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch(
    "https://json.extendsclass.com/bin/26301d924e23"
  );
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};
